name: Add Labels 
# The events that triggers the workflow
on:
  pull_request_target:
    branches:
      - master
    types:
      - opened

jobs:
  add-label:
    name: Add Labels
    # The machine each job should run
    runs-on: ubuntu-latest
    # The tasks each job should run
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
                   LGMSOC21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
